name: Generar y subir JSON automáticamente

on:
  workflow_dispatch:    # puedes cambiar el disparador a push, schedule, etc.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Crear archivo JSON
        uses: devops-actions/json-to-file@v1.0.4
        with:
          json: |
            {
              "name": "pipelines",
              "activity": 3,
              "module": 2,
              "isRequired": false
            }
          filename: archivo.json

      - name: Subir archivo.json como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: archivo-json
          path: archivo.json
