name: Clasificación de edades

on:
  workflow_dispatch:
    inputs:
      dia:
        description: 'Ingresa el día de nacimiento (DD)'
        required: true
        type: string
      mes:
        description: 'Ingresa el mes de nacimiento (MM)' 
        required: true
        type: string
      anio:
        description: 'Ingresa el año de nacimiento (YYYY)'
        required: true
        type: string

env:
  LIM_NINEZ: ${{ vars.LIM_NINEZ }}
  LIM_ADOLESCENCIA: ${{ vars.LIM_ADOLESCENCIA }}
  LIM_ADULTO_JOVEN: ${{ vars.LIM_ADULTO_JOVEN }}
  LIM_ADULTO: ${{ vars.LIM_ADULTO }}

jobs:
  calcular_edad:
    name: Calculo Edad
    runs-on: ubuntu-latest
    outputs:
      edad: ${{ steps.edad.outputs.edad }}
    steps:
      - name: Realizar calculo
        id: edad
        run: |
          dia=${{ github.event.inputs.dia }}
          mes=${{ github.event.inputs.mes }}
          anio=${{ github.event.inputs.anio }}

          echo "Fecha de nacimiento: $anio-$mes-$dia"

          current_day=$(date +%d)
          current_month=$(date +%m)
          current_year=$(date +%Y)

          # Convertir a enteros base 10 para evitar problemas con ceros a la izquierda
          dia_nac=$((10#$dia))
          mes_nac=$((10#$mes))
          anio_nac=$((10#$anio))
          day_now=$((10#$current_day))
          month_now=$((10#$current_month))
          year_now=$((10#$current_year))

          edad=$((year_now - anio_nac))
          meses=$((month_now - mes_nac))
          dias=$((day_now - dia_nac))

          # Paso 1: Ajustar días si negativos
          if [ "$dias" -lt 0 ]; then
            meses=$((meses - 1))
            prev_month=$((month_now - 1))
            prev_year=$year_now
            if [ "$prev_month" -eq 0 ]; then
              prev_month=12
              prev_year=$((year_now - 1))
            fi
            dias_en_mes_anterior=$(cal $prev_month $prev_year | awk 'NF {DAYS = $NF}; END {print DAYS}')
            dias=$((dias + dias_en_mes_anterior))
          fi

          # Paso 2: Ajustar edad si el cumpleaños aún no ha llegado
          if [ "$meses" -lt 0 ]; then
            edad=$((edad - 1))
            meses=$((meses + 12))
          fi

          echo "Edad exacta: $edad años, $meses meses, $dias días"

          echo "edad=$edad" >> $GITHUB_OUTPUT
          echo "meses=$meses" >> $GITHUB_OUTPUT
          echo "dias=$dias" >> $GITHUB_OUTPUT

  clasificacion_edad:
    name: Clasificación
    needs: calcular_edad
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje según resultado
        run: |
          edad=${{ needs.calcular_edad.outputs.edad }}
          echo "Edad calculada: $edad"

          if [ "$edad" -lt "$LIM_NINEZ" ]; then
            echo "Etapa: Niñez"
          elif [ "$edad" -lt "$LIM_ADOLESCENCIA" ]; then
            echo "Etapa: Adolescencia"
          elif [ "$edad" -lt "$LIM_ADULTO_JOVEN" ]; then
            echo "Etapa: Adultos Jóvenes"
          elif [ "$edad" -lt "$LIM_ADULTO" ]; then
            echo "Etapa: Adultos"
          else
            echo "Etapa: Vejez"
          fi
