name: Clasificación de edades

on:
  workflow_dispatch:
    inputs:
      dia:
        description: 'Ingresa el día de nacimiento (DD)'
        required: true
        type: string
      mes:
        description: 'Ingresa el mes de nacimiento (MM)' 
        required: true
        type: string
      anio:
        description: 'Ingresa el año de nacimiento (YYYY)'
        required: true
        type: string

env:
  LIM_NINEZ: ${{ vars.LIM_NINEZ }}
  LIM_ADOLESCENCIA: ${{ vars.LIM_ADOLESCENCIA }}
  LIM_ADULTO_JOVEN: ${{ vars.LIM_ADULTO_JOVEN }}
  LIM_ADULTO: ${{ vars.LIM_ADULTO }}

jobs:
  calcular_edad:
    name: Calculo Edad
    runs-on: ubuntu-latest
    outputs:
      edad: ${{ steps.edad.outputs.edad }}
    steps:
      - name: Realizar calculo
        id: edad
        run: |
          dia=${{ github.event.inputs.dia }}
          mes=${{ github.event.inputs.mes }}
          anio=${{ github.event.inputs.anio }}

          echo "Fecha de nacimiento: $anio-$mes-$dia"

          # Fecha actual en formato YYYY-MM-DD
          hoy=$(date +%Y-%m-%d)
          nacimiento=$(printf "%04d-%02d-%02d" "$anio" "$mes" "$dia")

          # Usar GNU date para obtener diferencia total en años, meses y días
          edad=$(dateutils.ddiff "$nacimiento" "$hoy" -f '%Y')
          meses=$(dateutils.ddiff "$nacimiento" "$hoy" -f '%m')
          dias=$(dateutils.ddiff "$nacimiento" "$hoy" -f '%d')

          echo "Edad exacta: $edad años, $meses meses, $dias días"

          echo "edad=$edad" >> $GITHUB_OUTPUT
          echo "meses=$meses" >> $GITHUB_OUTPUT
          echo "dias=$dias" >> $GITHUB_OUTPUT


  clasificacion_edad:
    name: Clasificación
    needs: calcular_edad
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje según resultado
        run: |
          edad=${{ needs.calcular_edad.outputs.edad }}
          echo "Edad calculada: $edad"

          if [ "$edad" -lt "$LIM_NINEZ" ]; then
            echo "Etapa: Niñez"
          elif [ "$edad" -lt "$LIM_ADOLESCENCIA" ]; then
            echo "Etapa: Adolescencia"
          elif [ "$edad" -lt "$LIM_ADULTO_JOVEN" ]; then
            echo "Etapa: Adultos Jóvenes"
          elif [ "$edad" -lt "$LIM_ADULTO" ]; then
            echo "Etapa: Adultos"
          else
            echo "Etapa: Vejez"
          fi
