name: Clasificación de edades
on:
  push:
    branches:
      - 'test1/*'
  workflow_dispatch:
    inputs:
      dia:
        description: 'Ingresa el día de nacimiento'
        required: true
        type: string
      mes:
        description: 'Ingresa el mes de nacimiento'
        required: true
        type: string
      anio:
        description: 'Ingresa el año de nacimiento'
        required: true
        type: string
env:
      LIM_NINEZ: ${{ vars.LIM_NINEZ }}
      LIM_ADOLESCENCIA: ${{ vars.LIM_ADOLESCENCIA }}
      LIM_ADULTO_JOVEN: ${{ vars.LIM_ADULTO_JOVEN }}
      LIM_ADULTO: ${{ vars.LIM_ADULTO }}

jobs:
  sumar_numeros:
    name: Calculo Edad
    runs-on: ubuntu-latest
    steps:
      - name: Realizar calculo
        id: suma
        run: |
          anio=${{ github.event.inputs.anio }}
          mes=${{ github.event.inputs.mes }}
          dia=${{ github.event.inputs.mes }}
          anio_actual=$(date +%Y)
          mes_actual=$(date +%m)
          dia_actual=$(date +%d)

          fecha_nacimiento=$(date -d "$anio-$mes-$dia" +%s)
          fecha_hoy=$(date +%s)

          dias_totales=$(( (fecha_hoy - fecha_nacimiento) / 86400))

          anios=$(( dias_totales / 365))
          meses=$(( (dias_totales % 365) / 30 ))
          dias=$(( (dias_totales % 365) % 30 ))

          echo "Fecha de nacimiento: $anio-$mes-$dia"
          echo "Edad aproximada: $anios años, $meses meses, $dias días"

  evaluar_resultado:
    name: Clasificación
    needs: sumar_numeros
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje según resultado
        run: |
          anio=${{ github.event.inputs.anio }}
          if [[ $anio -lt $LIM_NINEZ ]]; then
            echo "edad $anio y limite $LIM_NINEZ"
            echo "Etapa: Niñez"
          elif [[ $anio -lt $LIM_ADOLESCENCIA ]]; then
              echo "Etapa Adolescencia"
              echo "edad $anio y limite $LIM_ADOLESCENCIA"
            elif [[ $anio -lt $LIM_ADULTO_JOVEN ]]; then
              echo "Etapa Adultos jovenes"
              echo "edad $anio y limite $LIM_ADULTO_JOVEN"
                elif [[ $anio -lt $LIM_ADULTO ]]; then
                  echo "Etapa Adultos"
                  echo "edad $anio y limite $LIM_ADULTO"
                else
                echo "Etapa de Vejez"
          fi