name: Clasificación de edades

on:
  workflow_dispatch:
    inputs:
      dia:
        description: 'Ingresa el día de nacimiento (DD)'
        required: true
        type: string
      mes:
        description: 'Ingresa el mes de nacimiento (MM)' 
        required: true
        type: string
      anio:
        description: 'Ingresa el año de nacimiento (YYYY)'
        required: true
        type: string

env:
  LIM_NINEZ: ${{ vars.LIM_NINEZ }}
  LIM_ADOLESCENCIA: ${{ vars.LIM_ADOLESCENCIA }}
  LIM_ADULTO_JOVEN: ${{ vars.LIM_ADULTO_JOVEN }}
  LIM_ADULTO: ${{ vars.LIM_ADULTO }}

jobs:
  calcular_edad:
    name: Calculo Edad
    runs-on: ubuntu-latest
    outputs:
      edad: ${{ steps.edad.outputs.edad }}
    steps:
      - name: Realizar calculo
        id: edad
        run: |
          dia=${{ github.event.inputs.dia }}
          mes=${{ github.event.inputs.mes }}
          anio=${{ github.event.inputs.anio }}

          echo "Fecha de nacimiento: $anio-$mes-$dia"

          # Fecha actual
          current_day=$(date +%d)
          current_month=$(date +%m)
          current_year=$(date +%Y)

          edad=$((current_year - anio))
          meses=$((current_month - mes))
          dias=$((current_day - dia))

          # Ajuste si el cumpleaños no ha pasado este año
          if [ "$meses" -lt 0 ] || { [ "$meses" -eq 0 ] && [ "$dias" -lt 0 ]; }; then
            edad=$((edad - 1))
            meses=$((meses + 12))
          fi

          # Ajuste de días si el día aún no ha llegado este mes
          if [ "$dias" -lt 0 ]; then
            meses=$((meses - 1))
            prev_month=$((10#$current_month - 1))
            prev_year=$current_year
            if [ "$prev_month" -eq 0 ]; then
              prev_month=12
              prev_year=$((current_year - 1))
            fi
            dias_en_mes_anterior=$(cal $prev_month $prev_year | awk 'NF {DAYS = $NF}; END {print DAYS}')
            dias=$((dias + dias_en_mes_anterior))
          fi

          echo "Edad exacta: $edad años, $meses meses, $dias días"

          echo "edad=$edad" >> $GITHUB_OUTPUT
          echo "meses=$meses" >> $GITHUB_OUTPUT
          echo "dias=$dias" >> $GITHUB_OUTPUT

  clasificacion_edad:
    name: Clasificación
    needs: calcular_edad
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje según resultado
        run: |
          edad=${{ needs.calcular_edad.outputs.edad }}
          echo "Edad calculada: $edad"

          if [ "$edad" -lt "$LIM_NINEZ" ]; then
            echo "Etapa: Niñez"
          elif [ "$edad" -lt "$LIM_ADOLESCENCIA" ]; then
            echo "Etapa: Adolescencia"
          elif [ "$edad" -lt "$LIM_ADULTO_JOVEN" ]; then
            echo "Etapa: Adultos Jóvenes"
          elif [ "$edad" -lt "$LIM_ADULTO" ]; then
            echo "Etapa: Adultos"
          else
            echo "Etapa: Vejez"
          fi
