name: Clasificación de edades

on:
  workflow_dispatch:
    inputs:
      dia:
        description: 'Ingresa el día de nacimiento (DD)'
        required: true
        type: string
      mes:
        description: 'Ingresa el mes de nacimiento (MM)' 
        required: true
        type: string
      anio:
        description: 'Ingresa el año de nacimiento (YYYY)'
        required: true
        type: string

env:
  LIM_NINEZ: ${{ vars.LIM_NINEZ }}
  LIM_ADOLESCENCIA: ${{ vars.LIM_ADOLESCENCIA }}
  LIM_ADULTO_JOVEN: ${{ vars.LIM_ADULTO_JOVEN }}
  LIM_ADULTO: ${{ vars.LIM_ADULTO }}

jobs:
  calcular_edad:
    name: Calculo Edad
    runs-on: ubuntu-latest
    outputs:
      edad: ${{ steps.edad.outputs.edad }}
    steps:
      - name: Realizar calculo
        id: edad
        run: |
          dia=${{ github.event.inputs.dia }}
          mes=${{ github.event.inputs.mes }}
          anio=${{ github.event.inputs.anio }}

          echo "Fecha ingresada: $anio-$mes-$dia"

          fecha_nacimiento=$(date -d "$anio-$mes-$dia")
          fecha_actual=$(date)

          dias_totales=$(( (fecha_actual - fecha_nacimiento)))
          anios=$(( dias_totales / 365 ))
          meses=$(( (dias_totales / 30 ))
          dias=$(( (dias_totales / 30 ))
          echo "Edad aproximada: $anios años, $meses meses, $dias días"
          echo "edad=$anios" >> $GITHUB_OUTPUT

  clasificacion_edad:
    name: Clasificación
    needs: calcular_edad
    runs-on: ubuntu-latest
    steps:
      - name: Mostrar mensaje según resultado
        run: |
          edad=${{ needs.calcular_edad.outputs.edad }}
          echo "Edad calculada: $edad"

          if [ "$edad" -lt "$LIM_NINEZ" ]; then
            echo "Etapa: Niñez"
          elif [ "$edad" -lt "$LIM_ADOLESCENCIA" ]; then
            echo "Etapa: Adolescencia"
          elif [ "$edad" -lt "$LIM_ADULTO_JOVEN" ]; then
            echo "Etapa: Adultos Jóvenes"
          elif [ "$edad" -lt "$LIM_ADULTO" ]; then
            echo "Etapa: Adultos"
          else
            echo "Etapa: Vejez"
          fi
